# Generated by Django 4.2.1 on 2023-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(upload_to='card_img')),
                ('Product_title', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_hading_img', models.ImageField(upload_to='card_hading')),
                ('product_help_img', models.ImageField(upload_to='card_help')),
                ('product_help_desc', models.ImageField(upload_to='card_help')),
                ('product_Features1', models.CharField(blank=True, max_length=100, null=True)),
                ('product_Features2', models.CharField(blank=True, max_length=100, null=True)),
                ('product_Features3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_img')),
                ('Hading_img', models.ImageField(upload_to='site_img')),
                ('Hading_text', models.CharField(max_length=200)),
                ('Hading_desc_text', models.CharField(max_length=200)),
                ('About_us_text', models.CharField(max_length=1000)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('address', models.CharField(max_length=1000)),
                ('Email', models.IntegerField()),
            ],
        ),
    ]
