# Generated by Django 4.2.1 on 2023-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contectform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedata',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
