# Generated by Django 4.2.1 on 2023-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_websitedata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='product_help_desc',
            field=models.CharField(max_length=200),
        ),
    ]
